# Changes here will be overwritten by Copier
_commit: v2.0.5
_src_path: gh:lincc-frameworks/python-project-template
author_email: ncaplar@uw.edu
author_name: Neven Caplar
create_example_module: false
custom_install: true
enforce_style:
- ruff_lint
- ruff_format
- black
failure_notification: []
include_benchmarks: false
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: scipy_2025_lsdb_nested
project_license: MIT
project_name: scipy_2025_lsdb_nested
project_organization: lincc-frameworks
python_versions:
- '3.10'
- '3.11'
- '3.12'
